### ISSUE TITLE
delete fields from models form

### ISSUE THREAD

**Issue by victazzz** [EscolaLMS/Admin#431]
for delete

- [x] base_price
- [ ] consultation duration
- [ ] webinar duration

**Comment by HerbertIV** [comment]
I removed fields base_price from consultations and webinars package. I sugest left duration with detail packages, because duration refers to them directly example consultation have a 2 hours duration not the product but product have a quantity and base_price.  I suggest added to extended models method getDuration and add getDuration to Product interface.
@qunabu @pa-cholek ?
